install:
 - brew update && brew install swiftlint
language: swift
osx_image: xcode11.6
xcode_project: mentorship ios.xcodeproj # path to your xcodeproj folder
xcode_scheme:
 - mentorship iosTests
 - mentorship iosUITests
xcode_destination: platform=iOS Simulator,OS=13.5,name=iPhone 8
script:
 - swiftlint
