before_install:
 - gem install cocoapods
install:
 - brew update && brew upgrade swiftlint
 - pod install
language: swift
osx_image: xcode11.6
xcode_workspace: mentorship ios.xcworkspace # path to your xcodeproj folder
xcode_scheme: mentorship iosTests
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 8
script:
 - swiftlint
 - xcodebuild test -workspace 'mentorship ios.xcworkspace' -scheme 'mentorship iosTests' -destination 'platform=iOS Simulator,OS=13.6,name=iPhone 8'
